version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: lemp-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build: .
    container_name: lemp-php
    volumes:
      - ./app:/var/www/html

  db:
    image: mysql:8.0
    container_name: lemp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # phpMyAdmin para administrar la base de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: lemp-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: always

volumes:
  db_data:
